### ISSUE TITLE
我把时钟从8M改到24M, msh 启动不正常

### ISSUE THREAD

**Issue by hanzo258** [Javesun99/Air001_rtt#2]
经过调试后, 发现在rt_hw_context_switch_to这个函数之前是正常的, 但是函数执行后msh的位置就出现乱码.  输入输出都是.
rt_hw_context_switch_to是个汇编函数. 看不懂.

8Mhz时能正常运作,  8M之外4M, 16M ,24M均是乱码

**Comment by Javesun99** [comment]
能否提供一下你修改的代码截图？

**Comment by hanzo258** [comment]
![微信图片_20240602170214](https://github.com/Javesun99/Air001_rtt/assets/51979841/1590c7a5-57d2-45cd-aa91-be0cf9fcd1ea)
![微信图片_20240602170223](https://github.com/Javesun99/Air001_rtt/assets/51979841/48bfecef-57cb-4a6e-9f23-320f0d95a397)

这是设置为8M,   (你的
![Uploading 微信图片_20240602170227.png…]()
代码默认也是8M),,结果是正常的
8M时msh界面正常,24M时乱码,

**Comment by hanzo258** [comment]
![微信图片_20240602170230](https://github.com/Javesun99/Air001_rtt/assets/51979841/cb2687c7-c753-4f70-98fa-bd827c4a7f11)
![微信图片_20240602170230](https://github.com/Javesun99/Air001_rtt/assets/51979841/771892b5-c17a-43dd-98cd-47f714e78cd8)

**Comment by Javesun99** [comment]
请仔细看看system_air001xxx.c这个文件，时钟调整应该在这部分

**Comment by hanzo258** [comment]
> 请仔细看看system_air001xxx.c这个文件，时钟调整应该在这部分

但是我只改了8M和24M这一个地方, 怎么会出现两种现象呢.
void SystemInit(void)
{
  /* Set the HSI clock to 8MHz by default */
  RCC->ICSCR = (RCC->ICSCR & 0xFFFF0000) | (0x1 << 13) | *(uint32_t *)(0x1fff0f04);

**Comment by Javesun99** [comment]
请根据官方手册修改
